OpenBanking-Brasil/specs-seguranca

open-banking-brasil-financial-api-1_ID1.md

https://github.com/OpenBanking-Brasil/specs-seguranca/issues/3
Closes #3 Adding Privacy and Consent Requirements

Closes #3 Adding Privacy and Consent Requirements

---

open-banking-brasil-dynamic-client-registration-1_ID1.md
open-banking-brasil-financial-api-1_ID1.md

Resolves #2, resolves #5, - Updated References and removed reference to consent specification

---

open-banking-brasil-financial-api-1_ID1.html
open-banking-brasil-financial-api-1_ID1.xml

Adding in RFC Generated HTML and XML for Security Profile Implementers Draft 1

Adding in RFC Generated HTML and XML for Security Profile

---

open-banking-brasil-financial-api-1_ID1.html
open-banking-brasil-financial-api-1_ID1.md
open-banking-brasil-financial-api-1_ID1.xml

closes #12
A note has been added on the documentation tickets to make sure the examples are updated to reflect

closes #12 - This changes the format of the cpf and cnpj claims to string

---

open-banking-brasil-dynamic-client-registration-1_ID1.md

Adjusting the text to point to the correct RFCs

Fixing the RFC# for these pointers

---

open-banking-brasil-dynamic-client-registration-1_ID1.html
open-banking-brasil-dynamic-client-registration-1_ID1.md
open-banking-brasil-dynamic-client-registration-1_ID1.xml

Closes #78 
as requested by Renan - regenerate the HTML for the DCR specification. The mark down was previously correct so there are no normative changes.

Closes #78

---

aspsp-user-guide.md
open-banking-brasil-certificate-standards-1_ID1.md
tpp-user-guide.md

Ajustes no texto e correções gramaticais. O item "Convenções Notacionais" foi totalmente alterado para o conteúdo que o Mario Ginglass fez para o documento do FAPI.

Padrão de Certificados / ASPSP  / TPP - Ajustes no texto e correções gramaticais

---

open-banking-brasil-certificate-standards-1_ID1.html
open-banking-brasil-certificate-standards-1_ID1.xml

Documento open-banking-brasil-certificate-standards-1_ID1.md convertido para html e xml

Versões html e xml

---

all-documents.md

Ajustes no DCR e guia de transmissoras, além de alguns ajustes nos itens iniciais (antes do FAPI).

Ajustes texto inicial, DCR e guia de transmissoras

---

all-documents.md
open-banking-brasil-certificate-standards-1_ID1.html
open-banking-brasil-dynamic-client-registration-1_ID1-ptbr.md
open-banking-brasil-dynamic-client-registration-1_ID1.md
tpp-user-guide.md

Fix #134 - add resources scope to regulatory roles DADOS e CONTAS

---

open-banking-brasil-financial-api-1_ID2-ptbr.md
open-banking-brasil-financial-api-1_ID2.md
open-banking-brasil-financial-api-1_ID3-ptbr.md
open-banking-brasil-financial-api-1_ID3.md

Ajustes para refletir decisões sobre requisitos para assinaturas de payloads usando JWS.

Requisitos para assinaturas de payloads usando JWS.

---

open-banking-brasil-dynamic-client-registration-1_ID2-ptbr.html
open-banking-brasil-dynamic-client-registration-1_ID2-ptbr.md
open-banking-brasil-dynamic-client-registration-1_ID2.html
open-banking-brasil-dynamic-client-registration-1_ID2.md

Remove Consents and Resources from required scopes for PAGTO DCR Clients. #213 
Included the Swagger Link into DCR PT-br Standard.

 Remove Consents and Resources from required scopes for PAGTO DCR Clients. #213 

---

open-banking-brasil-financial-api-1_ID3-ptbr.md
open-banking-brasil-financial-api-1_ID3.md

Atualização do item 6.2

---

open-banking-brasil-financial-api-1_ID3-ptbr.md

Correção referente à issue 164.

Alteração de "valido" para status "authorized"

---

open-banking-brasil-financial-api-1_ID3.md

Referring to issue 164: Changes word "valid" to "with AUTHORIZED status"
Referring to issue 227:  Instructions about what to do in cases not specified in the documentation.

164 and 227 issues

---

open-banking-brasil-financial-api-1_ID3-ptbr.md

Issue 227 - Instrução sobre casos não previstos na especificação.

Issue 227 - Instrução sobre casos não previstos

---

open-banking-brasil-certificate-standards-1_ID1-ptbr.md

* **organizationIdentifier:** Código de Participante associado ao CNPJ listado no Serviço de Diretório do Open Finance Brasil; Para certificados emitidos até 31 de Agosto o campo utilizado para essa informação é o organizationalUnitName.
* **organizationIdentifier (OID 2.5.4.97):** Código de Participante associado ao CNPJ listado no Serviço de Diretório do Open Finance Brasil. *Para certificados emitidos até 31 Agosto de 2022: **organizationalUnitName (OID 2.5.4.11):** Código de Participante associado ao CNPJ listado no Serviço de Diretório do Open Finance Brasil
* **organizationIdentifier (OID 2.5.4.97):** Nome da Autoridade Certificadora. *Para certificados emitidos até 31 Agosto de 2022: **organizationalUnitName (OID 2.5.4.11):** Nome da Autoridade Certificadora
* …

Alteração em 5.2.2.1, 5.2.3.1, 8.1, 8.2

---

open-banking-brasil-certificate-standards-1_ID1-ptbr.html

organizationIdentifier = OFBBR-&lt;Código de Participante&gt;
--
0.organizationalUnitName = &lt;Autoridade Certificadora&gt;
1.organizationalUnitName = &lt;CNPJ da Autoridade Registradora&gt;
2.organizationalUnitName = &lt;Tipo de validação&gt;

Correção 8.1.2 e 8.2.2

---

open-banking-brasil-dynamic-client-registration-1_ID2.md

Adição do subject_dn validado com a Serasa.

Proibição do campo OU - DCR - Ajustes md ingles

---

open-banking-brasil-dynamic-client-registration-1_ID2-ptbr.html

Adição do subject_dn validado com a Serasa.

Proibição do campo OU - DCR - Ajustes html ptbr

---

open-banking-brasil-dynamic-client-registration-1_ID2.html

Adição do subject_dn validado com a Serasa.

Proibição do campo OU - DCR - Ajustes html ingles

---

dcr_review/dcr-dcm-swagger.yaml

Inclusão tls_client_auth_subject_dn

tls_client_auth_subject_dn no Swagger/DCR

---

open-banking-brasil-financial-api-CIBA-1_ID1.md

Change of login-hint-token-type from "opaque" to "ephemeral"

Change CIBA

---

open-banking-brasil-certificate-standards-1_ID1-ptbr.html
open-banking-brasil-certificate-standards-1_ID1-ptbr.md
open-banking-brasil-certificate-standards-1_ID1.html
open-banking-brasil-certificate-standards-1_ID1.md

Preview:
- https://refined-github-html-preview.kidonng.workers.dev/OpenBanking-Brasil/specs-seguranca/raw/iti-urls/open-banking-brasil-certificate-standards-1_ID1-ptbr.html#section-5.2.3.2
- https://refined-github-html-preview.kidonng.workers.dev/OpenBanking-Brasil/specs-seguranca/raw/iti-urls/open-banking-brasil-certificate-standards-1_ID1.html#name-participating-certificate-a

Referencia direta para repositórios ITI

---

open-banking-brasil-certificate-standards-1_ID1-ptbr.html
open-banking-brasil-certificate-standards-1_ID1-ptbr.md

Preview:
- https://refined-github-html-preview.kidonng.workers.dev/OpenBanking-Brasil/specs-seguranca/raw/iti-urls/open-banking-brasil-certificate-standards-1_ID1-ptbr.html#section-5.2.3.2

ITI URLs - Typo fix

---

dcr_review/dcr-dcm-swagger.yaml

Não é possível utilizar ":" dentro de uma descrição, por tando tive de retira-la.

Fix swagger format

---

open-banking-brasil-dynamic-client-registration-1_ID3-ptbr.md

Removido subitem 1;
Adicionado subitem 3.

Atualização item 9.3.2 registration_access_token

---

open-banking-brasil-dynamic-client-registration-1_ID3-ptbr.html

Removido subitem 1;
Adicionado subitem 3.

Atualização item 9.3.2 html/ptbr

---

open-banking-brasil-dynamic-client-registration-1_ID2.html

Removido subitem 1;
Adicionado subitem 3.

Atualização item 9.3.2 html/eng

---

open-banking-brasil-dynamic-client-registration-1_ID2.md

Removido subitem 1;
Adicionado subitem 3.

Atualização item 9.3.2 md/eng

---

open-banking-brasil-financial-api-1_ID3-ptbr.md

Adição de informação para padronização de  tempo de expiração do campo request_uri

Padronização de request_uri md/ptbr

---

open-banking-brasil-financial-api-1_ID3.md

Adição de informação para padronização de tempo de expiração do campo request_uri

Padronização de request_uri md/eng

---

open-banking-brasil-certificate-standards-1_ID2-ptbr.md

Padrão de Certificados ID2 com novo Subject DN do Certificado Cliente Open Finance - Após 19 de janeiro de 2023

Certificates new id2 new subject dn standard

---

open-banking-brasil-financial-api-1_ID3-ptbr.html
open-banking-brasil-financial-api-1_ID3-ptbr.md
open-banking-brasil-financial-api-1_ID3.html
open-banking-brasil-financial-api-1_ID3.md

Alterações nos itens 5.2 e 5.2.3

Inclusão do item x-fapi-interation-id

---

tpp-user-guide-ptbr.md

Foi feita a seguinte alteração:
4.3.4, o seguinte ajuste deve ser realizado:
•	
•	
•	Na primeira linha do exemplo do item 1. Check a consent resource, o exemplo deve ser alterado conforme instrução abaixo:
•	
o	
o	
o	De:
o	curl --cert transport.pem --key transport.key -H 'Authorization: Bearer 2Pjwts8m1KRZmm0aJyXbOTB8zRosN55fo8Ewdulhxxa'
o	
o	
o	
o	Para:
o	curl --cert transport.pem --key transport.key -H 'Authorization: Bearer 2Pjwts8m1KRZmm0aJyXbOTB8zRosN55fo8Ewdulhxxa'
o	 -H ‘x-fapi-interaction-id: 8b6cd915-2b59-44c4-9848-47b97a8aa368’

Fix: Modified line 709 of tpp-user-guide-ptbr file

---

dcr_review/dcr-dcm-swagger.yaml

Incluido no Swagger o atributo maxLength para o campo redirect_uris.

maxLength para o campo redirect_uris
