OpenBanking-Brasil/specs-seguranca

- open-banking-brasil-financial-api-1_ID1-ptbr.html
- open-banking-brasil-financial-api-1_ID1-ptbr.md
- open-banking-brasil-financial-api-1_ID1.html
- open-banking-brasil-financial-api-1_ID1.md
Closes #95 - The name of the specification was correct, the advanced profile of FAPI however the number was not.
> Addressing typo in specification, the 'Advanced' profile is Part 2 not Part 1

- all-documents.md
- open-banking-brasil-financial-api-1_ID1-ptbr.md
Corrige issue #112 para indicar opcional atributos que não fazem sentido para instituições que só tratam PF.
Pessoal, mantive a proposta do PR #120 aberto pelo @RalphBragg, mas questiono sobre a opcionalidade da claim CPF, pois entendo que essa não deveria ser opcional.
Fix Bug #112 .  @GislaineAlmeida, @DeiGratia33 and @alex-siqueira would you please check my comment at #120 ? As we always have a person authenticatiing aganst ASPSP system and giving his consent to share data, even when he selected a business account (assuming UX is going to give some option to a user select an especific account), at the end, we always have a CPF that should be related to an account / authentication, right @GislaineAlmeida @alex-siqueira ? If it is true, we have to keep line 4 as it was originally.
> bug/112 pt_BR

- certificate-generation-instructions/brcac.cnf
- certificate-generation-instructions/brseal.cnf
- open-banking-brasil-certificate-standards-1_ID1-ptBR.md
- open-banking-brasil-certificate-standards-1_ID1.md
- open-banking-brasil-financial-api-1_ID1-ptbr.md
- open-banking-brasil-financial-api-1_ID1.md
- uml/consent-process-redirect.uml
- uml/dynamic-client-registartion.uml
- Created certificate standard in english
- Updated cnf files to represent the same content of the appendix
- Sugestion of clarification about the refresh_token issuing and expiration
- Updated UML to remove OCSP and name ICP-Brasil and ICP-Brasil CA
> certificate standard english

- open-banking-brasil-financial-api-1_ID3-ptbr.md
- open-banking-brasil-financial-api-1_ID3.md
Inclusão da documentação da proibição da rotação do refresh token conforme decisão do conselho deliberativo votado na 87ª reunião e solicitado pelo GT de segurança a atualização da documentação relativa ao item.
> Inclusão da documentação da proibição da rotação do refresh token

- open-banking-brasil-dynamic-client-registration-1_ID2.md
The PTBR DCR DCM doc has a sentence:
Observação: A [RFC7592] prevê a possibilidade de rotação do registration_access_token emitido pelo Servidor de Autorização a cada uso, tornando-o um token de uso único. As instituições devem considerar esse aspecto no registro de suas aplicações cliente para receber e atualizar o registration_access_token pelo novo valor recebido nas chamadas de manutenção de cliente.
It's just a translated version to adjust the docs:
Note: [RFC7592] provides the possibility of rotating the `registration_access_token` issued by the Authorization Server with each use, making it a single-use token. When registering their client applications, institutions should consider this aspect to receive and update the `registration_access_token` for the new value received in client …
> Include a note into DCR/DCM to match PT-BR Doc #198

- open-banking-brasil-financial-api-1_ID3-ptbr.md
- open-banking-brasil-financial-api-1_ID3.md
1. Numeração diverge da aprovada, pois havia sido baseada no HTML que
encontra-se desatualizado
2. Incluído o texto "para o ambiente do Open Banking" no item 20, por
que se não, iria impedir o uso do Servidor de Autorização para outras
funcionalidades, se tivesse configuração diversa da certificada.
> ft_id05_wellknown

- open-banking-brasil-financial-api-1_ID3-ptbr.md
- open-banking-brasil-financial-api-1_ID3.md
- Equalizada numeração de linhas para facilitar comparação
- Link para a FAPI-2 Advanced disponível só em Inglês
- Em inglês não pedia que retornasse o CPF da pessoa autenticada
- Em portugues nâo incluia texto informando que o perfil definia duas novas classes de ACR
- "ICP Brasileiro" ao invés de "ICP Brasil"
- Texto em inglês duplicado na versão portugues
> Versions Sync

- idtoken_review/README.md
- open-banking-brasil-financial-api-1_ID3-ptbr.md
- open-banking-brasil-financial-api-1_ID3.md
1. Numeração diverge da aprovada, pois havia sido baseada no HTML que
encontra-se desatualizado
2. Incluído o texto "para o ambiente do Open Banking" no item 20, por
que se não, iria impedir o uso do Servidor de Autorização para outras
funcionalidades, se tivesse configuração diversa da certificada.
> ft_id57_idtoken_encryption

- open-banking-brasil-dynamic-client-registration-1_ID2-ptbr.html
Criação:
<li id="section-9.3.1-1.4">não devem ser permitidos múltiplos cadastros DCR para o mesmo Software Statement , de forma que em caso de tentativa de novo registro para um Software Statement já cadastrado, deve se utilizar o procedimento de Error Response definido no item 3.2.2 da <a href="https://tools.ietf.org/html/rfc7591">RFC7591</a>.<a href="#section-9.3.1-1.4" class="pilcrow">¶</a>
</li>
Alteração:
<li id="section-9.3.1-1.5">emitir, na resposta do registro, um <code>registration_access_token</code> para ser usado como token de autenticação nas opera&#231;&#245;es de manuten&#231;&#227;o da aplica&#231;&#227;o cliente registrada, seguindo as especifica&#231;&#245;es descritas na <a href="https://tools.ietf.org/html/rfc7592">RFC7592</a>.<a href="#section-9.3.1-1.5" …
> Alteração do item 9.3.4 para 9.3.5, Criação do item 9.3.4

- open-banking-brasil-dynamic-client-registration-1_ID2-ptbr.md
Criação:
4. não devem ser permitidos múltiplos cadastros DCR para o mesmo Software Statement , de forma que em caso de tentativa de novo registro para um Software Statement já cadastrado, deve se utilizar o procedimento de Error Response definido no item 3.2.2 da RFC7591.
Alteração:
5. emitir, na resposta do registro, um `registration_access_token` para ser usado como token de autenticação nas operações de manutenção da aplicação cliente registrada, seguindo as especificações descritas na [RFC7592].
> Alteração do 9.3.4 para 9.3.5, Criação do 9.3.4

- open-banking-brasil-dynamic-client-registration-1_ID2-ptbr.md
Inserido novos campos
[...]
13. O valor do campo *UID* do certificado deve coincidir com o enviado no SSA, onde o campo *UID* deve conter o valor do campo *software_id* do SSA.
14. O valor do campo *organizationIdentifier* do certificado deve conter  o prefixo correspondente ao Registration Reference *OFBBR-* seguido do valor do campo *org_id* do SSA. 
Para certificados emitidos até 31 de Agosto de 2022: o valor do campo *OU* do certificado deve conter o valor do campo *org_id* do SSA.
15. deve, durante o processo de handshake TLS, usar a regra `distinguishedNameMatch` para comparar os valores DN conforme definido na [RFC4517].
16. deve ser garantido a todos, após os mesmos atos de consentimentos permanentes, para que também sejam alterados para instituições receptoras de dados …
> Alteração em 7.1 e 9.3.1

- open-banking-brasil-dynamic-client-registration-1_ID2-ptbr.html
Novo texto: 
[...]
<li id="section-7.1-3.13">O valor do campo <em>UID</em> do certificado deve coincidir com o enviado no SSA, onde o campo <em>UID</em> deve conter o valor do campo <em>software_id</em> do SSA.<a href="#section-7.1-3.13" class="pilcrow">¶</a>
</li>
<li id="section-7.1-3.14">O valor do campo <em>organizationIdentifier</em> do certificado deve conter o prefixo correspondente ao Registration Reference <em>OFBBR-</em> seguido do valor do campo <em>org_id</em> do SSA. Para certificados emitidos até 31 de Agosto de 2022: o valor do campo <em>OU</em> do certificado deve conter o valor do campo <em>org_id</em> do SSA.<a href="#section-7.1-3.14" class="pilcrow">¶</a>
</li>
<li id="section-7.1-3.15">deve, durante o processo de handshake TLS, usar a regra …
> Campo OU - Alteração em 7.1 e 9.3.1

- open-banking-brasil-dynamic-client-registration-1_ID2.html
New text:
[...]
<li id="section-7.1-3.13">the value of the field <em>UID</em> of the certificate should match the one sent in the SSA, where the <em>UID</em> field should contain the value of the <em>software_id</em> field of the SSA.<a href="#section-7.1-3.13" class="pilcrow">¶</a>
</li>
<li id="section-7.1-3.14">the value of the filed <em>organizationIdentifier</em> of the certificate shall contain the prefix corresponding to the Registration Reference <em>OFBBR-</em> followed by the value of the <em>org_id</em> field of the SSA. <br/> For certificates issued until 31 August 2022: the value of the <em>OU</em> field of the certificate shall contain the value of the <em>org_id</em> field of the SSA.<a href="#section-7.1-3.14" class="pilcrow">¶</a>
</li>
<li id="section-7.1-3.15">shall, …
> Campo OU - Alteracao em 7.1 e 9.3.1

- open-banking-brasil-certificate-standards-1_ID1-ptbr.html
Removido as informações inseridas sobre o campo organizationIdentifier no certificado de assinatura, pois isso nao será necessário - sessões [5.2.3.1.] e [8.2].
Adicionado novas informações para o modelo de geração de .csr para certificados de cliente - sessão 8.1.2
> Proibição do campo OU - Certificados - Ajustes html ptbr

- open-banking-brasil-certificate-standards-1_ID1-ptbr.md
Removido as informações inseridas sobre o campo organizationIdentifier no certificado de assinatura, pois isso nao será  necessário - sessões [5.2.3.1.] e [8.2]. 
Adicionado novas informações para o modelo de geração de .csr  para certificados de cliente - sessão 8.1.2
> Proibição do campo OU - Certificados - Ajustes md ptbr

- open-banking-brasil-financial-api-1_ID3-ptbr.html
Adição das informações no item 5.2.2:
18. deve garantir que em caso de compartilhamento do Servidor de Autorização para outros serviços, além do Open Finance, não divulgue e/ou possibilite o uso de métodos não certificados no ambiente do Open Finance;
19. deve garantir que as configurações divulgadas aos demais participantes através do `OpenID Discovery` (indicado pelo arquivo de `Well-Known` cadastrado no Diretório) sejam restritos aos modos de operação aos quais a instituição se certificou;
1. deve manter em suas configurações os métodos para os quais ainda hajam clientes ativos;
2. deve atualizar os cadastros que utilizem métodos não certificados, através de tratamento bilateral entre as instituições envolvidas.
20. deve recusar requisições, para o ambiente do Open Finance, que estejam …
> Padronização de request_uri html/ptbr

- open-banking-brasil-financial-api-1_ID3.html
Adição das informações no item 5.2.2:
18. shall ensure that, in case of sharing the Authorization Server for other services, in addition to Open Finance, it does not disclose and/or allow the use of non-certified methods in the Open Finance environment;
19. shall ensure that the settings disclosed to other participants through `OpenID Discovery` (indicated by the `Well-Known` file registered in the Directory) are restricted to the operating modes to which the institution has certified;
1. shall keep in your settings the methods for which there are still active clients;
2. shall update the records that use non-certified methods, through bilateral treatment between the institutions involved.
20. shall refuse requests, for the Open Finance environment, that are outside the modes of operation …
> Padronização de request_uri html/eng

- dcr_review/dcr-dcm-swagger.yaml
O Swagger do DCR não estava seguindo os exemplos da [RFC7591](https://datatracker.ietf.org/doc/html/rfc7591). Esta PR resolve este problema para evitar problemas de interoperabilidade.
> Swagger do DCR seguindo RFC7591

- tpp-user-guide-ptbr.md
Como solicitado a linha 560 foi alterada :
De: curl --cert transport.pem --key transport.key -H 'Authorization: Bearer 2Pjwts8m1KRZmm0aJyXbOTB8zRosN55fo8Ewdulhxxa' Para: curl --cert transport.pem --key transport.key -H 'Authorization: Bearer 2Pjwts8m1KRZmm0aJyXbOTB8zRosN55fo8Ewdulhxxa' -H ‘x-fapi-interaction-id: ff36560a-11d2-44b1-ace3-2327b077a103’
A linha 544 foi inserida:
Todas as chamadas para endpoints FAPI devem conter o cabeçalho x-fapi-interaction-id.
> Fix: Alterada linha 560 e Incluida linha 544

- dcr_review/dcr-dcm-swagger.yaml
Adicionado o atributo webhook_uris no body da requisição do POST DCR e PUT DCM. Adicionado a opção invalid_webhook_uris no ENUM dos erros permitidos no POST DCR e PUT DCM
> Adição de parâmetros de webhook no DCR/DCM

- dcr_review/dcr-dcm-swagger.yaml
Correção de typo no atributo require_pushed_authorization_requests que antes estava nomeado como require_pushed_authorization_request
> Correção de typo no atributo require_pushed_authorization_requests
